// Mocks generated by Mockito 5.4.4 from annotations
// in prestador_de_servico/test/helpers/service_schedulingk/mock_service_scheduling_repository.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:prestador_de_servico/app/models/service_scheduling/service_scheduling.dart'
    as _i6;
import 'package:prestador_de_servico/app/repositories/service_scheduling/service_scheduling_repository.dart'
    as _i3;
import 'package:prestador_de_servico/app/shared/either/either.dart' as _i2;
import 'package:prestador_de_servico/app/shared/failure/failure.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ServiceSchedulingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockServiceSchedulingRepository extends _i1.Mock
    implements _i3.ServiceSchedulingRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ServiceScheduling>>> getAllByDay(
          {required DateTime? dateTime}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllByDay,
          [],
          {#dateTime: dateTime},
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.Failure, List<_i6.ServiceScheduling>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.ServiceScheduling>>(
          this,
          Invocation.method(
            #getAllByDay,
            [],
            {#dateTime: dateTime},
          ),
        )),
        returnValueForMissingStub: _i4
            .Future<_i2.Either<_i5.Failure, List<_i6.ServiceScheduling>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.ServiceScheduling>>(
          this,
          Invocation.method(
            #getAllByDay,
            [],
            {#dateTime: dateTime},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ServiceScheduling>>>);

  @override
  _i4.Future<
      _i2.Either<_i5.Failure, List<_i6.ServiceScheduling>>> getAllByUserId(
          {required String? userId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllByUserId,
          [],
          {#userId: userId},
        ),
        returnValue: _i4
            .Future<_i2.Either<_i5.Failure, List<_i6.ServiceScheduling>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.ServiceScheduling>>(
          this,
          Invocation.method(
            #getAllByUserId,
            [],
            {#userId: userId},
          ),
        )),
        returnValueForMissingStub: _i4
            .Future<_i2.Either<_i5.Failure, List<_i6.ServiceScheduling>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.ServiceScheduling>>(
          this,
          Invocation.method(
            #getAllByUserId,
            [],
            {#userId: userId},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ServiceScheduling>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, DateTime>> getDateOfFirstService() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDateOfFirstService,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, DateTime>>.value(
            _FakeEither_0<_i5.Failure, DateTime>(
          this,
          Invocation.method(
            #getDateOfFirstService,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, DateTime>>.value(
                _FakeEither_0<_i5.Failure, DateTime>(
          this,
          Invocation.method(
            #getDateOfFirstService,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, DateTime>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, DateTime>> getDateOfLastService() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDateOfLastService,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, DateTime>>.value(
            _FakeEither_0<_i5.Failure, DateTime>(
          this,
          Invocation.method(
            #getDateOfLastService,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, DateTime>>.value(
                _FakeEither_0<_i5.Failure, DateTime>(
          this,
          Invocation.method(
            #getDateOfLastService,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, DateTime>>);
}
