// Mocks generated by Mockito 5.4.4 from annotations
// in prestador_de_servico/test/helpers/payment/mock_payment_repository.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:prestador_de_servico/app/models/payment/payment.dart' as _i6;
import 'package:prestador_de_servico/app/repositories/payment/payment_repository.dart'
    as _i3;
import 'package:prestador_de_servico/app/shared/utils/either/either.dart'
    as _i2;
import 'package:prestador_de_servico/app/shared/utils/failure/failure.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PaymentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentRepository extends _i1.Mock implements _i3.PaymentRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Payment>>> getAll() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Payment>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Payment>>(
          this,
          Invocation.method(
            #getAll,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Payment>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Payment>>(
          this,
          Invocation.method(
            #getAll,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Payment>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Payment>>> getUnsync(
          {required DateTime? dateLastSync}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsync,
          [],
          {#dateLastSync: dateLastSync},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Payment>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Payment>>(
          this,
          Invocation.method(
            #getUnsync,
            [],
            {#dateLastSync: dateLastSync},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Payment>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Payment>>(
          this,
          Invocation.method(
            #getUnsync,
            [],
            {#dateLastSync: dateLastSync},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Payment>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> insert(
          {required _i6.Payment? payment}) =>
      (super.noSuchMethod(
        Invocation.method(
          #insert,
          [],
          {#payment: payment},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #insert,
            [],
            {#payment: payment},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, String>>.value(
                _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #insert,
            [],
            {#payment: payment},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> update(
          {required _i6.Payment? payment}) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [],
          {#payment: payment},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #update,
            [],
            {#payment: payment},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
                _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #update,
            [],
            {#payment: payment},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> deleteById(
          {required String? id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteById,
          [],
          {#id: id},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #deleteById,
            [],
            {#id: id},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
                _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #deleteById,
            [],
            {#id: id},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> existsById({required String? id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #existsById,
          [],
          {#id: id},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #existsById,
            [],
            {#id: id},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
                _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #existsById,
            [],
            {#id: id},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);
}
