// Mocks generated by Mockito 5.4.4 from annotations
// in prestador_de_servico/test/app/repositories/service_category/service_category_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:prestador_de_servico/app/models/service_category/service_cartegory.dart'
    as _i2;
import 'package:prestador_de_servico/app/repositories/service_category/service_category_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeServiceCategory_0 extends _i1.SmartFake
    implements _i2.ServiceCategory {
  _FakeServiceCategory_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ServiceCategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockServiceCategoryRepository extends _i1.Mock
    implements _i3.ServiceCategoryRepository {
  @override
  _i4.Future<List<_i2.ServiceCategory>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i4.Future<List<_i2.ServiceCategory>>.value(
            <_i2.ServiceCategory>[]),
        returnValueForMissingStub: _i4.Future<List<_i2.ServiceCategory>>.value(
            <_i2.ServiceCategory>[]),
      ) as _i4.Future<List<_i2.ServiceCategory>>);

  @override
  _i4.Future<_i2.ServiceCategory> getById({required String? id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getById,
          [],
          {#id: id},
        ),
        returnValue:
            _i4.Future<_i2.ServiceCategory>.value(_FakeServiceCategory_0(
          this,
          Invocation.method(
            #getById,
            [],
            {#id: id},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.ServiceCategory>.value(_FakeServiceCategory_0(
          this,
          Invocation.method(
            #getById,
            [],
            {#id: id},
          ),
        )),
      ) as _i4.Future<_i2.ServiceCategory>);

  @override
  _i4.Future<List<_i2.ServiceCategory>> getNameContained(
          {required String? name}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNameContained,
          [],
          {#name: name},
        ),
        returnValue: _i4.Future<List<_i2.ServiceCategory>>.value(
            <_i2.ServiceCategory>[]),
        returnValueForMissingStub: _i4.Future<List<_i2.ServiceCategory>>.value(
            <_i2.ServiceCategory>[]),
      ) as _i4.Future<List<_i2.ServiceCategory>>);

  @override
  _i4.Future<String> insert({required _i2.ServiceCategory? serviceCategory}) =>
      (super.noSuchMethod(
        Invocation.method(
          #insert,
          [],
          {#serviceCategory: serviceCategory},
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #insert,
            [],
            {#serviceCategory: serviceCategory},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #insert,
            [],
            {#serviceCategory: serviceCategory},
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> update({required _i2.ServiceCategory? serviceCategory}) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [],
          {#serviceCategory: serviceCategory},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteById({required String? id}) => (super.noSuchMethod(
        Invocation.method(
          #deleteById,
          [],
          {#id: id},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
